spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true


apis:
  url:
    kakaoapi: "https://dapi.kakao.com"
    naver: "https://openapi.naver.com/v1/search/blog.json"
